# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alejo/Documentos/HB/KISA_LOP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alejo/Documentos/HB/KISA_LOP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alejo/Documentos/HB/KISA_LOP/CMakeFiles /home/alejo/Documentos/HB/KISA_LOP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alejo/Documentos/HB/KISA_LOP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named order_crossover_testing

# Build rule for target.
order_crossover_testing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 order_crossover_testing
.PHONY : order_crossover_testing

# fast build rule for target.
order_crossover_testing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/build
.PHONY : order_crossover_testing/fast

#=============================================================================
# Target rules for targets named swap_testing

# Build rule for target.
swap_testing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swap_testing
.PHONY : swap_testing

# fast build rule for target.
swap_testing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/build
.PHONY : swap_testing/fast

src/GA/GA.o: src/GA/GA.cpp.o
.PHONY : src/GA/GA.o

# target to build an object file
src/GA/GA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/GA.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/GA.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/GA.cpp.o
.PHONY : src/GA/GA.cpp.o

src/GA/GA.i: src/GA/GA.cpp.i
.PHONY : src/GA/GA.i

# target to preprocess a source file
src/GA/GA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/GA.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/GA.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/GA.cpp.i
.PHONY : src/GA/GA.cpp.i

src/GA/GA.s: src/GA/GA.cpp.s
.PHONY : src/GA/GA.s

# target to generate assembly for a file
src/GA/GA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/GA.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/GA.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/GA.cpp.s
.PHONY : src/GA/GA.cpp.s

src/GA/crossover.o: src/GA/crossover.cpp.o
.PHONY : src/GA/crossover.o

# target to build an object file
src/GA/crossover.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/crossover.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/crossover.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/crossover.cpp.o
.PHONY : src/GA/crossover.cpp.o

src/GA/crossover.i: src/GA/crossover.cpp.i
.PHONY : src/GA/crossover.i

# target to preprocess a source file
src/GA/crossover.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/crossover.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/crossover.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/crossover.cpp.i
.PHONY : src/GA/crossover.cpp.i

src/GA/crossover.s: src/GA/crossover.cpp.s
.PHONY : src/GA/crossover.s

# target to generate assembly for a file
src/GA/crossover.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/crossover.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/crossover.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/crossover.cpp.s
.PHONY : src/GA/crossover.cpp.s

src/GA/mutation.o: src/GA/mutation.cpp.o
.PHONY : src/GA/mutation.o

# target to build an object file
src/GA/mutation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/mutation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/mutation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/mutation.cpp.o
.PHONY : src/GA/mutation.cpp.o

src/GA/mutation.i: src/GA/mutation.cpp.i
.PHONY : src/GA/mutation.i

# target to preprocess a source file
src/GA/mutation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/mutation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/mutation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/mutation.cpp.i
.PHONY : src/GA/mutation.cpp.i

src/GA/mutation.s: src/GA/mutation.cpp.s
.PHONY : src/GA/mutation.s

# target to generate assembly for a file
src/GA/mutation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/mutation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/mutation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/mutation.cpp.s
.PHONY : src/GA/mutation.cpp.s

src/GA/parent_selection.o: src/GA/parent_selection.cpp.o
.PHONY : src/GA/parent_selection.o

# target to build an object file
src/GA/parent_selection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/parent_selection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/parent_selection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/parent_selection.cpp.o
.PHONY : src/GA/parent_selection.cpp.o

src/GA/parent_selection.i: src/GA/parent_selection.cpp.i
.PHONY : src/GA/parent_selection.i

# target to preprocess a source file
src/GA/parent_selection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/parent_selection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/parent_selection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/parent_selection.cpp.i
.PHONY : src/GA/parent_selection.cpp.i

src/GA/parent_selection.s: src/GA/parent_selection.cpp.s
.PHONY : src/GA/parent_selection.s

# target to generate assembly for a file
src/GA/parent_selection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/parent_selection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/parent_selection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/parent_selection.cpp.s
.PHONY : src/GA/parent_selection.cpp.s

src/GA/population_selection.o: src/GA/population_selection.cpp.o
.PHONY : src/GA/population_selection.o

# target to build an object file
src/GA/population_selection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/population_selection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/population_selection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/population_selection.cpp.o
.PHONY : src/GA/population_selection.cpp.o

src/GA/population_selection.i: src/GA/population_selection.cpp.i
.PHONY : src/GA/population_selection.i

# target to preprocess a source file
src/GA/population_selection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/population_selection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/population_selection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/population_selection.cpp.i
.PHONY : src/GA/population_selection.cpp.i

src/GA/population_selection.s: src/GA/population_selection.cpp.s
.PHONY : src/GA/population_selection.s

# target to generate assembly for a file
src/GA/population_selection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GA/population_selection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA/population_selection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA/population_selection.cpp.s
.PHONY : src/GA/population_selection.cpp.s

src/GA_testing/Crossover/order_crossover_testing.o: src/GA_testing/Crossover/order_crossover_testing.cpp.o
.PHONY : src/GA_testing/Crossover/order_crossover_testing.o

# target to build an object file
src/GA_testing/Crossover/order_crossover_testing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA_testing/Crossover/order_crossover_testing.cpp.o
.PHONY : src/GA_testing/Crossover/order_crossover_testing.cpp.o

src/GA_testing/Crossover/order_crossover_testing.i: src/GA_testing/Crossover/order_crossover_testing.cpp.i
.PHONY : src/GA_testing/Crossover/order_crossover_testing.i

# target to preprocess a source file
src/GA_testing/Crossover/order_crossover_testing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA_testing/Crossover/order_crossover_testing.cpp.i
.PHONY : src/GA_testing/Crossover/order_crossover_testing.cpp.i

src/GA_testing/Crossover/order_crossover_testing.s: src/GA_testing/Crossover/order_crossover_testing.cpp.s
.PHONY : src/GA_testing/Crossover/order_crossover_testing.s

# target to generate assembly for a file
src/GA_testing/Crossover/order_crossover_testing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/GA_testing/Crossover/order_crossover_testing.cpp.s
.PHONY : src/GA_testing/Crossover/order_crossover_testing.cpp.s

src/GA_testing/Mutation/swap_testing.o: src/GA_testing/Mutation/swap_testing.cpp.o
.PHONY : src/GA_testing/Mutation/swap_testing.o

# target to build an object file
src/GA_testing/Mutation/swap_testing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA_testing/Mutation/swap_testing.cpp.o
.PHONY : src/GA_testing/Mutation/swap_testing.cpp.o

src/GA_testing/Mutation/swap_testing.i: src/GA_testing/Mutation/swap_testing.cpp.i
.PHONY : src/GA_testing/Mutation/swap_testing.i

# target to preprocess a source file
src/GA_testing/Mutation/swap_testing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA_testing/Mutation/swap_testing.cpp.i
.PHONY : src/GA_testing/Mutation/swap_testing.cpp.i

src/GA_testing/Mutation/swap_testing.s: src/GA_testing/Mutation/swap_testing.cpp.s
.PHONY : src/GA_testing/Mutation/swap_testing.s

# target to generate assembly for a file
src/GA_testing/Mutation/swap_testing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/GA_testing/Mutation/swap_testing.cpp.s
.PHONY : src/GA_testing/Mutation/swap_testing.cpp.s

src/IO.o: src/IO.cpp.o
.PHONY : src/IO.o

# target to build an object file
src/IO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/IO.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/IO.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/IO.cpp.o
.PHONY : src/IO.cpp.o

src/IO.i: src/IO.cpp.i
.PHONY : src/IO.i

# target to preprocess a source file
src/IO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/IO.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/IO.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/IO.cpp.i
.PHONY : src/IO.cpp.i

src/IO.s: src/IO.cpp.s
.PHONY : src/IO.s

# target to generate assembly for a file
src/IO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/IO.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/IO.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/IO.cpp.s
.PHONY : src/IO.cpp.s

src/LOP.o: src/LOP.cpp.o
.PHONY : src/LOP.o

# target to build an object file
src/LOP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/LOP.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/LOP.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/LOP.cpp.o
.PHONY : src/LOP.cpp.o

src/LOP.i: src/LOP.cpp.i
.PHONY : src/LOP.i

# target to preprocess a source file
src/LOP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/LOP.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/LOP.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/LOP.cpp.i
.PHONY : src/LOP.cpp.i

src/LOP.s: src/LOP.cpp.s
.PHONY : src/LOP.s

# target to generate assembly for a file
src/LOP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/LOP.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/LOP.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/LOP.cpp.s
.PHONY : src/LOP.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/memory.o: src/memory.cpp.o
.PHONY : src/memory.o

# target to build an object file
src/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/memory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/memory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/memory.cpp.o
.PHONY : src/memory.cpp.o

src/memory.i: src/memory.cpp.i
.PHONY : src/memory.i

# target to preprocess a source file
src/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/memory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/memory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/memory.cpp.i
.PHONY : src/memory.cpp.i

src/memory.s: src/memory.cpp.s
.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/memory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order_crossover_testing.dir/build.make CMakeFiles/order_crossover_testing.dir/src/memory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swap_testing.dir/build.make CMakeFiles/swap_testing.dir/src/memory.cpp.s
.PHONY : src/memory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... order_crossover_testing"
	@echo "... swap_testing"
	@echo "... src/GA/GA.o"
	@echo "... src/GA/GA.i"
	@echo "... src/GA/GA.s"
	@echo "... src/GA/crossover.o"
	@echo "... src/GA/crossover.i"
	@echo "... src/GA/crossover.s"
	@echo "... src/GA/mutation.o"
	@echo "... src/GA/mutation.i"
	@echo "... src/GA/mutation.s"
	@echo "... src/GA/parent_selection.o"
	@echo "... src/GA/parent_selection.i"
	@echo "... src/GA/parent_selection.s"
	@echo "... src/GA/population_selection.o"
	@echo "... src/GA/population_selection.i"
	@echo "... src/GA/population_selection.s"
	@echo "... src/GA_testing/Crossover/order_crossover_testing.o"
	@echo "... src/GA_testing/Crossover/order_crossover_testing.i"
	@echo "... src/GA_testing/Crossover/order_crossover_testing.s"
	@echo "... src/GA_testing/Mutation/swap_testing.o"
	@echo "... src/GA_testing/Mutation/swap_testing.i"
	@echo "... src/GA_testing/Mutation/swap_testing.s"
	@echo "... src/IO.o"
	@echo "... src/IO.i"
	@echo "... src/IO.s"
	@echo "... src/LOP.o"
	@echo "... src/LOP.i"
	@echo "... src/LOP.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

